certfile='C:\\keys\\planq.tk-chain.pem'
keyfile='C:\\keys\\planq.tk-key.pem'
mysql_host='kalut.ml'
mysql_user='kalut'
# mysql_pwd=''
mysql_pwd_path='C:\\keys\\pwd.txt'
mysql_database='kalut'
host='192.168.1.160'
restapi_port=25565
sock_port=50000