certfile='/etc/letsencrypt/live/kalut.ml/fullchain.pem'
keyfile='/etc/letsencrypt/live/kalut.ml/privkey.pem'
mysql_host='localhost'
mysql_user='kalut'
# mysql_pwd=''
mysql_pwd_path='/home/ronyu/Desktop/pwd.txt'
mysql_database='kalut'
host='10.0.1.6'
restapi_port=50001
sock_port=50000